
public enum Especialidad {
	
	ODONTOLOGIA, CARDIOLOGIA, CLINICA_MEDICA, ECOGRAFIAS, RADIOGRAFIAS, RESONANCIA_MAGNETICA, GINECOLOGIA,
	TRAUMATOLOGIA, ERGOMETRIA, EXTRACCION_SANGRE, CIRUGIA, DERMATOLOGIA

}
